imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
     format: d.m.Y, H:i:s
     interval_format: '%%d days'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    sender_address: '%mailer_user%'
    spool: { type: memory }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

#KNP paginator
knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

#Vich Uploader
vich_uploader:
    db_driver: orm
    mappings:
            recording_mp3:
                uri_prefix:         /assets/recordings
                upload_destination: '%kernel.root_dir%/../web/assets/recordings'
                namer:              vich_uploader.namer_uniqid

                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            profile_documents:
                uri_prefix:         /assets/documents
                upload_destination: '%kernel.root_dir%/../web/assets/documents'
                namer:              vich_uploader.namer_uniqid

                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

#Crysoft Mpesa Bundle
crysoft_mpesa:
    mpesa:
        endpoint:           https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest                   # The M-Pesa API Endpoint.
        token_endpoint:     https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials   # Mpesa API Token Endpoint
        status_endpoint:    https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query                  # Mpesa API Status Endpoint
        callback_url:       http://id.crysoftlabs.com/mpesa/update/                                   # The callback URL to be queried on transaction completion.
        callback_method:    POST               # The callback method to be used.
        paybill_number:     174379               # The merchant's Paybill number.
        pass_key:           bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919                     # The SAG Passkey given on registration.
        consumer_key:       0q3P2fyn9wTx9A3IxuFHKenA1PtUrcwL
        consumer_secret:    6G8E3Pd0ADxlXIeo

